/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inyeccion;

import com.google.inject.Guice;
import com.google.inject.Injector;
import inyeccion.services.ConducirService;
import inyeccion.services.FabricaVehiculosService;
import inyeccion.services.impl.HondaService;
import inyeccion.entities.TiposVehiculos;
import inyeccion.entities.Vehiculo;
import inyeccion.modules.VehiculosModule;

public class App {
    public static void main(String[] args) {

        Injector injector = Guice.createInjector(new VehiculosModule());

        FabricaVehiculosService hondaArgentina = injector.getInstance(HondaService.class);

        Vehiculo vehiculo;
        vehiculo = hondaArgentina.fabricarAuto();
        System.out.println(vehiculo.toString());
        System.out.println("produccion= " + hondaArgentina.getContadorProduccion());


        ConducirService conducirService = injector.getInstance(ConducirService.class);
        conducirService.conducir(vehiculo);


        //vehiculo = hondaArgentina.fabricarMoto();
        //System.out.println(vehiculo.toString());
        //System.out.println("produccion= " + hondaArgentina.getContadorProduccion());

        //FabricaVehiculosService hondaColombia = injector.getInstance(HondaService.class);
        //vehiculo = hondaColombia.fabricar(TiposVehiculos.BARCO);
        //System.out.println(vehiculo.toString());

        //System.out.println("produccion= " + hondaColombia.getContadorProduccion());
    }
}
